app/Http/Controllers/TablesController.php
app/Models/Table.php
app/Services/Scoring.php
tests/_support/ApiTester.php
tests/api/TablesCest.php

GDF-120: added default title and description for table

GDF-120: added default title and description for table

---

app/Http/Controllers/TablesController.php
composer.lock
tests/api/TablesCest.php

GDF-131: added validation for reserved word "webhook" into fields keys

GDF-131: added validation for reserved word "webhook" into fields keys

---

app/Http/Controllers/GroupsController.php
app/Models/Group.php
app/Models/Table.php
app/Observers/TableObserver.php
app/Providers/ValidationServiceProvider.php
app/Repositories/GroupsRepository.php
app/Repositories/TablesRepository.php
app/Validators/GroupValidator.php
app/Validators/TableValidator.php
composer.json
composer.lock
tests/_support/ApiTester.php
tests/api/GroupsCest.php

GDF-147: Group.Tables sync

---

app/Http/Controllers/TablesController.php
app/Http/routes.php
app/Models/Condition.php
app/Repositories/TablesRepository.php
composer.lock
public/swagger.json
tests/_support/ApiTester.php
tests/api/TablesCest.php

GDF-127 - table analytics, doc, tests

GDF-127 - table analytics

---

.travis.yml
app/Http/Controllers/ConsumerController.php
app/Models/Decision.php
app/Models/Group.php
app/Services/Scoring.php
public/swagger.json
tests/_support/ApiTester.php
tests/api/DecisionsCest.php
tests/api/TablesCest.php

GDF-148: Added title and description for Group, added Group to Decision

GDF-148: added Group to Decision

---

app/Models/Rule.php
app/Services/Scoring.php
tests/_support/ApiTester.php
tests/api/DecisionsCest.php

GDF-158: added test for scoring Table

GDF-158: added test for scoring Table

---

app/Models/Rule.php
app/Repositories/TablesRepository.php
app/Services/ConditionsTypes.php
app/Services/Scoring.php
tests/api/DecisionsCest.php
tests/api/TablesCest.php

GDF-154: changed required rule to present for Decision Maker

GDF-154: changed required rule to present for Decision Maker

---

app/Http/Controllers/ConsumerController.php
app/Http/Controllers/DecisionsController.php
app/Http/Controllers/TablesController.php
app/Http/routes.php
app/Models/Decision.php
app/Providers/ValidationServiceProvider.php
app/Repositories/DecisionsRepository.php
app/Repositories/TablesRepository.php
public/swagger.json
resources/lang/en/validation.php
tests/_support/ApiTester.php
tests/api/DecisionsCest.php

GDF-5: Customer Meta Data

---

app/Exceptions/Handler.php
app/Models/Rule.php
app/Repositories/TablesRepository.php
app/Services/Scoring.php
tests/_support/ApiTester.php
tests/api/TablesCest.php

GDF-209 - count probabilities for rules

GDF-209 - count probabilities for rules

---

app/Providers/ObserverServiceProvider.php
bootstrap/app.php
composer.lock

GDF-211 - created ObserverServiceProvider

GDF-211 - created ObserverServiceProvider

---

app/Repositories/TablesRepository.php

GDF-210 use MongoClient instead of Eloquent

GDF-210 use MongoClient instead of Eloquent

---

app/Http/Controllers/TablesController.php
app/Repositories/TablesRepository.php
composer.lock
tests/api/TablesCest.php

GDF-220 - filtering by matching_type, test for filters

GDF-220 - filtering by matching_type, test for filters

---

app/Http/Controllers/TablesController.php
app/Observers/TableObserver.php
app/Services/Scoring.php
app/Validators/TableValidator.php
tests/api/GroupsCest.php
tests/api/TablesCest.php

GDF-249: do not delete condition for deleted field in Groups.Tables

GDF-249: do not delete condition for deleted field in Groups.Tables

---

app/Models/Group.php
tests/_support/ApiTester.php

GDF-251: send Group.description for list of groups

GDF-251: send Group.description for list of groups

---

app/Models/Decision.php
app/Services/Scoring.php
database/migrations/20160526175042_DecisionApplicationable.php
database/migrations/20160526180242_AddTableVariants.php

GDF-265: migration for Table.variants

GDF-265: migration for Table.variants

---

database/migrations/20160526180242_AddTableVariants.php
public/swagger.json

GDF-260: API doc for Table.variants

GDF-260: API doc for Table.variants

---

app/Exceptions/Handler.php
app/Http/Controllers/UsersController.php
composer.lock
config/applicationable.php
puppet/general/manifests/init.pp
tests/api/ProjectsCest.php
tests/api/UsersCest.php

Remove user from list of users during search,
List of scopes when 403 error,
Admin access to project

Remove user from list of users during search, List of scopes when 403 error, Admin access to project

---

app/Http/Controllers/ConsumerController.php
app/Services/Scoring.php
composer.lock
database/migrations/20160606143656_ProjectSettingsShowMeta.php
tests/_support/ApiTester.php
tests/api/DecisionsCest.php

GDF-375 - Project.settings, show_meta for consumer check

GDF-375 - Project.settings, show_meta for consumer check

---

app/Http/Controllers/UsersController.php
app/Validators/PasswordValidator.php
tests/_support/ApiTester.php
tests/api/UsersCest.php

GDF-343 - password validation length

GDF-343 - password validation length

---

apiary.apib
app/Observers/TableObserver.php
tests/api/TablesCest.php

GDF-404: set username to Changelog.author

GDF-404: set username to Changelog.author

---

apiary.apib
app/Exceptions/AdminIsNotActivatedException.php
app/Exceptions/Handler.php
bootstrap/app.php
composer.lock
config/errors.php
resources/lang/en/validation.php
tests/api/UsersCest.php

GDF-356: Doc errors

---

app/Models/Base.php
app/Repositories/TablesRepository.php
composer.lock
tests/api/TablesCest.php

GDF-310: analyze last version of Table

GDF-310: analyze last version of Table

---

apiary.apib
app/Models/Table.php
tests/_support/ApiTester.php

GDF-389: variants for TableList

GDF-389: variants for TableList

---

app/Http/routes.php
composer.lock
tests/api/DecisionsCest.php

GDF-383: validate in routes MongoID

GDF-383: validate in routes MongoID

---

app/Repositories/DecisionsRepository.php
composer.lock
database/migrations/20160621121112_DecisionsCreatedAtIndex.php

GDF-379: smart paginate from Lumen-REST

GDF-379: smart paginate from Lumen-REST

---

app/Models/Decision.php
tests/_support/ApiTester.php

GDF-435 - convert dates to ISO8601

GDF-435 - convert dates to ISO8601

---

apiary.apib
app/Http/Controllers/DecisionsController.php
app/Http/routes.php
app/Repositories/DecisionsRepository.php
tests/api/DecisionsCest.php

GDF-433 - filter decisions by variant_id

GDF-433 - filter decisions by variant_id

---

app/Http/Controllers/UsersController.php
app/Http/routes.php
app/Models/User.php
app/Repositories/UsersRepository.php
composer.lock
tests/api/UsersCest.php

GDF-427 - resend verify email token

GDF-427 - resend verify email token

---

apiary.apib
app/Http/Controllers/TablesController.php
app/Models/Table.php
app/Providers/ValidationServiceProvider.php
app/Repositories/DecisionsRepository.php
app/Validators/GeneralValidator.php
app/Validators/TableValidator.php
resources/lang/en/validation.php
tests/_support/ApiTester.php
tests/api/TablesCest.php

GDF-461: decision_type validator

GDF-461: decision_type validator

---

tests/api/TablesCest.php

GDF-489: fixed TableCest:betweenRule

GDF-489: fixed TableCest:betweenRule

---

database/migrations/2016_05_26_180242_AddTableVariants.php
database/migrations/2016_07_01_114918_TableDecisionType.php

GDF-490: fixed Variant migration, added migration for Table.decision_type

GDF-490: fixed Variant migration, added migration for Table.decision_type

---

tests/_support/ApiTester.php
tests/api/UsersCest.php

GDF-499: negative test for users/current

GDF-499: negative test for users/current

---

apiary.apib
app/Http/Controllers/UsersController.php
app/Http/routes.php
tests/api/UsersCest.php

GDF-514: username route validator

GDF-514: username route validator

---

apiary.apib
app/Events/Decisions/Make.php
app/Listeners/EventListener.php
app/Models/Decision.php
app/Services/Scoring.php
tests/_support/ApiTester.php

GDF-503: return one application_id for Decisions

GDF-503: return one application_id for Decisions

---

tests/api/UsersCest.php

test for tmp_email - field should be null after activation

test for tmp_email - field should be null after activation

---

app/Http/Controllers/UsersController.php
app/Providers/ValidationServiceProvider.php
app/Validators/UserValidator.php
tests/api/UsersCest.php

GDF-529: validator for email&username for User.update

GDF-529: validator for email&username for User.update

---

app/Http/Controllers/UsersController.php
app/Providers/ValidationServiceProvider.php
app/Repositories/UsersRepository.php
app/Validators/UserValidator.php
resources/lang/en/validation.php
tests/api/UsersCest.php

GDF-530: throw 422 instead of 401 for invalid current_password

GDF-530: throw 422 instead of 401 for invalid current_password
